baseURL               = "https://tgdh.github.io/"
languageCode          = "zh-CN"
title                 = "电报群组频道导航tgdh - Telegram频道群组导航"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"				# 站点静态文件保存目录


[params]
    author        = "Telegram百科"
    description   = "Telegram群组频道导航| 帮你找到最有趣最好玩的群组频道"
    upload        = "mailto:sobot1024@gmail.com"      # 左侧导航栏的"网站提交"
    about         = ""	          # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "Telegram群组频道导航"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					# 默认站点为深色(夜间)模式
    yiyan         = false                        		# 默认启用一言服务

[params.seo]
    baiduhmid       = '4f128523deb48dab18a4e51d2e24b16e'	# 百度统计 hm.src 的 ID
    baiduSiteVer    = 'codeva-cCAOSG8MBO'			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = 'ca-pub-5803807445434654'					# Google AdSense

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/telegram_bg.jpeg"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		# 搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，合作联系：<a href="mailto:sobot1024@gmail.com">sobot1024@gmail.com</a>或[@TG双向机器人](https://t.me/tghzsx_bot)<br/>&copy; 2023 - {year} By [Telegram](https://www.tgbaike.com) <br/>'
